site_name: Go DAV OS
site_url: https://dmarro89.github.io/go-dav-os/
use_directory_urls: false
theme:
  name: material
nav:
  - Home: index.md
  - Introduction: manual/00-introduction/README.md
  - Glossary: manual/00-introduction/glossary.md
  - Architecture: manual/01-overview/architecture.md
  - Boot & GRUB: manual/02-boot/boot-and-grub.md
  - Memory Layout: manual/02-boot/linker-and-initial-memory-layout.md
  - Privilege Transition: manual/03-kernel-core/privilege-transition-gdt-tss-rsp0.md
  - User/Kernel Memory Isolation: manual/03-kernel-core/user-kernel-memory-isolation.md
